import React from 'react';
import style from './searchresult.module.css';

const SearchResult = ({caption, timestamp, image, searchInput, videoUrl}) => {

  const getBoldedText = (text, input) => {
    var boldedTerms = {}
    var regexStr = ''
    input.split(' ').forEach(term => {
      boldedTerms[term.toLowerCase()] = true
      regexStr += term.toLowerCase() + '|'
    })

    const parts = text.split(new RegExp(`(${regexStr})`, 'gi'));
    return <span> { parts.map((part, i) =>
        <span key={i} style={part.toLowerCase() in boldedTerms? { fontWeight: 'bold' } : {} }>
            { part }
        </span>)
    } </span>;
  }

  return (
    <div className={style.searchresult}>
      <img src={'images/' + image} alt="" height="300" width="425"/>
      <p><b>Autogenerated Caption: </b></p>
      <p style={{ color: 'blue' }}>{getBoldedText(caption, searchInput)}</p>
      <p><b>Timestamp: </b><a href={videoUrl + "&t=" + timestamp} target="_blank">{timestamp}</a></p>
    </div>
  )
}

export default SearchResult;
